### ISSUE TITLE
Epic - MVP

### ISSUE THREAD

**Issue by joshuawilson** [talamer/vscode-knative#1]
### Description:
The knative extension allows the user to view and create knative services in a kubernetes environment. 

### Acceptance Criteria:
- [x] It should display the Services for an application / project / namespace
- [x] It should login to kubernetes #6, #8 
- [x] It should allow the user to deploy an image as a service #17

### Stretch goal:
- [x] It could display traffic splitting #26
- [x] It could display Revisions #25
